author: Márton Demcsik
title: "Energize Your Code: Adventures in Python & Machine Learning"
description: "Exploring Python and machine learning to improve energy efficiency."
url: "https://happiness133-python.github.io/skills-github-pages/"
baseurl: "/"
theme: "minima"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - _pages
sass:
  sass_dir: _sass
timezone: "Europe/Budapest"
