author: Márton Demcsik
title: "Energize Your Code: Adventures in Python & Machine Learning"
description: "Exploring Python and machine learning to improve energy efficiency."
url: "https://happiness133-python.github.io/skills-github-pages/"
baseurl: "/"
theme: "minima"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - _pages
sass:
  sass_dir: _sass
timezone: "Europe/Budapest"
